version: "3.9"
services:
  web:
    build:
      context: ./
    volumes:
      - ./:/kiosk
      - /kiosk/node_modules
    ports:
      - "8080:8080"
    environment: 
      - CHOKIDAR_USEPOLLING=true
