swagger: '2.0'
info:
  title: PeakBeyondApi
  description: Peak beyond api documentation
  contact:
    name: API Support
    url: 'http://www.open-api.io/support'
    email: support@open-api.io
  version: 1.0.0
host: 'peak-beyond-api-staging.herokuapp.com'
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
