export enum OrderStatus {
  VERIFICATION_PENDING = 'VERIFICATION_PENDING',
  AWAITING_PROCESSING = 'AWAITING_PROCESSING',
  IN_PROCESS = 'IN_PROCESS',
  PACKED_READY = 'PACKED_READY',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
}
