require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/store_category_taxes", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # StoreCategoryTax. As you add validations to StoreCategoryTax, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # StoreCategoryTaxesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      StoreCategoryTax.create! valid_attributes
      get store_category_taxes_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      store_category_tax = StoreCategoryTax.create! valid_attributes
      get store_category_tax_url(store_category_tax), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StoreCategoryTax" do
        expect {
          post store_category_taxes_url,
               params: { store_category_tax: valid_attributes }, headers: valid_headers, as: :json
        }.to change(StoreCategoryTax, :count).by(1)
      end

      it "renders a JSON response with the new store_category_tax" do
        post store_category_taxes_url,
             params: { store_category_tax: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StoreCategoryTax" do
        expect {
          post store_category_taxes_url,
               params: { store_category_tax: invalid_attributes }, as: :json
        }.to change(StoreCategoryTax, :count).by(0)
      end

      it "renders a JSON response with errors for the new store_category_tax" do
        post store_category_taxes_url,
             params: { store_category_tax: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested store_category_tax" do
        store_category_tax = StoreCategoryTax.create! valid_attributes
        patch store_category_tax_url(store_category_tax),
              params: { store_category_tax: invalid_attributes }, headers: valid_headers, as: :json
        store_category_tax.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the store_category_tax" do
        store_category_tax = StoreCategoryTax.create! valid_attributes
        patch store_category_tax_url(store_category_tax),
              params: { store_category_tax: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq("application/json")
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the store_category_tax" do
        store_category_tax = StoreCategoryTax.create! valid_attributes
        patch store_category_tax_url(store_category_tax),
              params: { store_category_tax: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested store_category_tax" do
      store_category_tax = StoreCategoryTax.create! valid_attributes
      expect {
        delete store_category_tax_url(store_category_tax), headers: valid_headers, as: :json
      }.to change(StoreCategoryTax, :count).by(-1)
    end
  end
end
