FROM ruby:2.7.0
RUN apt-get update -qq \
&& apt-get install --no-install-recommends -y nodejs postgresql-client-11 \
&& apt-get install --no-install-recommends shared-mime-info -y
RUN apt-get clean \
&& rm -rf /var/lib/apt/lists/*
COPY . /TPB-API
WORKDIR /TPB-API
RUN bundle install
EXPOSE 3000
RUN chmod 777 ./entrypoint_sidekiq.sh \
    && ln -s ./entrypoint_sidekiq.sh /
ENTRYPOINT ["./entrypoint_sidekiq.sh"]
