version: '3.8'
services:
  db:
    image: postgres:12.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tpb
      POSTGRES_PASSWORD: tpb    
      POSTGRES_DB: tpb_api
    volumes:
      - ~/.postgres/data/tpb:/var/lib/postgresql/data
  redis:
      build:
        context: ./redis
      image: myredis
      privileged: true
      command: sh -c "./init.sh"      
      ports:
        - 6379:6379
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/TPB-API
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    volumes:
      - .:/TPB-API
    env_file:
      - .env