source 'https://rubygems.org'

ruby '~> 3.0.0'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'pg'
gem 'rails', '~> 6.1.0'

# Use Puma as the app server
gem 'puma', '~> 5.6'

gem 'active_model_serializers', '~> 0.10.0'
gem 'activejob-uniqueness'
gem 'acts-as-taggable-on'
gem 'airbrake'
gem 'algoliasearch-rails'
gem 'aws-sdk-s3'
# Use Active Model has_secure_password
gem 'bcrypt'
gem 'dry-monads'
gem 'dry-validation'
gem 'httparty'
gem 'kaminari'
gem 'knock'
gem 'oj'
gem 'paper_trail'
gem 'pusher'
gem 'pundit'
gem 'rack'
gem 'rack-cors', require: 'rack/cors'
gem "sentry-ruby"
gem "sentry-rails"
gem "sidekiq"
gem 'sidekiq-cron'
gem 'twilio-ruby'
gem 'shopify_api'
gem "http"

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv-rails'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 2.23'
  gem 'fuubar', '~> 2.5'
  gem 'guard'
  gem 'guard-rails', require: false
  gem 'guard-rspec', require: false
  gem 'guard-spring', require: false
  gem 'hashdiff'
  gem 'pundit-matchers'
  gem 'rspec-rails', '~> 5.0'
  gem 'rspec_api_documentation'
  gem 'rspec_junit_formatter', '~> 0.6'
  gem 'rubocop', require: false
  gem 'rubocop-faker', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'spring-commands-rspec'
  gem 'timecop'
  gem 'webmock'
  gem 'simplecov', require: false
  gem 'simplecov-json', require: false
  gem 'database_cleaner-active_record', '~> 2.0'
end

group :development do
  gem 'listen', '~> 3.8'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'annotate'
  gem 'bullet'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :production, :staging do
  gem 'barnes'
  gem 'rack-timeout'
  gem 'rails_12factor'
end

group :production do
  gem 'scout_apm', '~> 5.3.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
